# Reference:
# - https://docs.docker.com/compose/compose-file
# - https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/
version: '3.8'
services:
  # Exposed server that's handling incoming web requests
  ohif_viewer:
    image: rajatimme/ohif:latest
    networks:
      - my_custom_network
    container_name: ohif_orthanc
    volumes:
      # Nginx config
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # Logs
      - ./logs/nginx:/var/logs/nginx
      # Let's Encrypt
      # - letsencrypt_certificates:/etc/letsencrypt
      # - letsencrypt_challenges:/var/www/letsencrypt
    ports:
      - '443:443' # SSL
      - '3000:80' # Web
    depends_on:
      #   - keycloak
      - orthanc
    restart: on-failure

  # LINK: https://hub.docker.com/r/jodogne/orthanc-plugins/
  # TODO: Update to use Postgres
  # https://github.com/mrts/docker-postgresql-multiple-databases
  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    container_name: orthancPACS
    networks:
      - my_custom_network
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    restart: unless-stopped
    ports:
      - '4243:4243' # Orthanc REST API
      - '8043:8043' # Orthanc HTTP

networks:
  my_custom_network:
    driver: bridge
