version: '3.8'
services:
  ohif_viewer:
    image: rajatimme/ohif:latest
    container_name: ohif_orthanc
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/logs/nginx
    networks:
      - my_custom_network
    ports:
      - '443:443' # SSL
      - '3000:80' # Web
    depends_on:
      - orthanc
    restart: unless-stopped 
          
  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    container_name: orthancPACS
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    restart: unless-stopped
    networks:
      - my_custom_network
    ports:
      - '4242:4242' 
      - '8042:8042' 

networks:
  my_custom_network:
    driver: bridge


